/**
 * One-shot generator for src/lib/leaderboard/regions.data.ts — the full GB/T
 * 2260 province + prefecture-city dataset.
 *
 * Source: `china-area-data` (installed transiently with --no-save; NOT a project
 * dependency). Re-run only when refreshing the administrative-division data:
 *   npm install --no-save china-area-data && node scripts/gen-regions.mjs
 *
 * We keep province (2-digit) + prefecture city (4-digit) codes, derived from the
 * package's 6-digit GB/T codes. Direct-administered municipalities (北京/天津/
 * 上海/重庆) collapse their single "市辖区" entry to the municipality name.
 */
import { createRequire } from "node:module";
import { writeFileSync } from "node:fs";

const require = createRequire(import.meta.url);
const data = require("china-area-data");

const provincesMap = data["86"]; // { "110000": "北京市", ... }

const provinces = [];
for (const [pcode6, pname] of Object.entries(provincesMap)) {
  const provinceCode = pcode6.slice(0, 2);
  const cityMap = data[pcode6] || {};
  const cities = [];
  const seen = new Set();
  for (const [ccode6, cnameRaw] of Object.entries(cityMap)) {
    const cityCode = ccode6.slice(0, 4);
    if (seen.has(cityCode)) continue; // 4-digit prefix is unique per prefecture
    seen.add(cityCode);
    // Municipalities have a single "市辖区" — show the municipality name instead.
    const name = cnameRaw === "市辖区" ? pname : cnameRaw;
    cities.push({ code: cityCode, name });
  }
  provinces.push({ code: provinceCode, name: pname, cities });
}

const cityTotal = provinces.reduce((n, p) => n + p.cities.length, 0);

const body = provinces
  .map((p) => {
    const cities = p.cities
      .map((c) => `    { code: "${c.code}", name: "${c.name}" },`)
      .join("\n");
    return `  {\n    code: "${p.code}",\n    name: "${p.name}",\n    cities: [\n${cities}\n    ],\n  },`;
  })
  .join("\n");

const file = `/**
 * China administrative divisions (GB/T 2260) — province (2-digit) + prefecture
 * city (4-digit). Used for the required, structured region picker (decision 2).
 *
 * GENERATED by scripts/gen-regions.mjs from the \`china-area-data\` package — do
 * not edit by hand; re-run the generator to refresh. ${provinces.length} provinces /
 * ${cityTotal} prefecture-level cities. Municipalities (北京/天津/上海/重庆) expose a
 * single city equal to the municipality.
 */
export interface CityData {
  code: string;
  name: string;
}

export interface ProvinceData {
  code: string;
  name: string;
  cities: CityData[];
}

export const PROVINCES: readonly ProvinceData[] = [
${body}
] as const;
`;

writeFileSync(new URL("../src/lib/leaderboard/regions.data.ts", import.meta.url), file, "utf8");
console.log(`wrote regions.data.ts: ${provinces.length} provinces, ${cityTotal} cities`);
